### ISSUE TITLE
Nil pointer {}.annotations error - Latest Helm Release 

### ISSUE THREAD

**Issue by armanjindal** [RasaHQ/rasa-x-helm#102]
Hello! I am very new to this, and I am in the process of setting up my CI/CD pipeline. The latest helm chart is giving me a bug. This is happening both in my [GH Actions](https://github.com/armanjindal/ecce-project_education/runs/1373076055?check_suite_focus=true) and on my local machine. I had the older version of the helm chart saved as 'rasa-x' and added the latest under 'rasa-x-new' and ran identical commands. The latter gave me an error. 

![Screen Shot 2020-11-10 at 11 50 32 AM](https://user-images.githubusercontent.com/58370547/98635685-7527e400-234b-11eb-9be9-eaebf1a3d524.png)

Given the recency of the release and changes to the specific code that is causing an error for me, I thought it worth bringing up. Thanks so much, and I appreciate any help!

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tczekajlo** [comment]
Hi @armanjindal,

It's not a bug, it's exactly how the helm works.

```
      --reuse-values                 when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored
```

You use the `--reuse-values` flag that makes you use computed values of the helm chart version that is installed, not the values built into the chart, that's why you see the error. 

You have several options to fix it:
- First of all, it's good to pin the helm chart to a specific version in order to avoid similar cases in the future
- You can get current values by executing `helm get values release_name -o yaml > values.yaml` and then, use them to upgrade the helm chart version, e.g. `helm upgrade rasa-x rasa-x/rasa-x -f values.yaml`
- You can use the `--reset-values` flag
```
 --reset-values                 when upgrading, reset the values to the ones built into the chart
```

**Comment by armanjindal** [comment]
Hi @tczekajlo. Thanks so much for your reply. That makes sense. Fixed the problem with the steps you recommended. Cheers!
