### ISSUE TITLE
docker.io/library/nginx:0.28.6: not found at install

### ISSUE THREAD

**Issue by mbricef** [RasaHQ/rasa-x-helm#181]
```
curl -s get-rasa-x.rasa.com | sudo bash
```
result at this error (seen in ubectl describe pod -n rasa rasa-nginx) :

```
Failed to pull image "nginx:0.28.6": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/nginx:0.28.6": failed to resolve reference "docker.io/library/nginx:0.28.6": docker.io/library/nginx:0.28.6: not found
```

**Comment by erohmensing** [comment]
Do you have an existing `values.yml` file? the tag for the image should be filled with this value otherwise: https://github.com/RasaHQ/rasa-x-helm/blob/main/charts/rasa-x/values.yaml#L480

**Comment by erohmensing** [comment]
Is this for a new install or an upgrade?

**Comment by mbricefree** [comment]
We use an old version of Rasa : 1.10.4 Which we would like not to upgrade for the moment. Regarding this fact our current rasaX version is 0.28.6. When resetting RasaX today with the server quick install script, we faced this issue for the first time.

We do not have an existing values.yml. 
Could the issue come from this part of the install script? :

  command=("${command[@]}"
    "--set rasax.tag=${RASA_X_VERSION}"
    "--set eventService.tag=${RASA_X_VERSION}"
    "--set nginx.tag=${RASA_X_VERSION}"
    "--set rasa.tag=${RASA_VERSION}-full"
  )

Because the tag set to nginx is the RASA_X_VERSION tag, which worked for rasa/nginx. But this tag will not work for nginx. from the rasa-x-1.8.7 update of https://github.com/RasaHQ/rasa-x-helm?

**Comment by erohmensing** [comment]
Yes exactly, you should be safe to not manually set that tag anymore, as we're using the standard nginx image instead of building one from rasa. I think that will work with the older rasa version 🤔 Otherwise you may need to stick to the older version of the chart.

**Comment by RASADSA** [comment]
will close this issues - it diverts from the default values of the helm chart.
