### ISSUE TITLE
Can't use the quick-install script to install Rasa X

### ISSUE THREAD

**Issue by lynndisco** [RasaHQ/rasa-x-helm#203]
When running server quick install script , I get an error

```
ubuntu@k3s:/Users/liyuan/Downloads$ curl -s get-rasa-x.rasa.com | sudo bash
Found existing cluster.
Installing Helm command line interface  ...
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
Error: looks like "https://rasahq.github.io/rasa-x-helm" is not a valid chart repository or cannot be reached: Get "https://rasahq.github.io/rasa-x-helm/index.yaml": x509: certificate has expired or is not yet valid: current time 2021-06-01T02:49:53+08:00 is after 2017-10-24T21:09:52Z
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @yennycheung will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by HotThoughts** [comment]
The problem is mostly like to be the connection with the https://rasahq.github.io/ website. 

Do you have proxy server/firewall enabled or anything that blocks you from accessing https://rasahq.github.io/?

Also, you have an existing cluster in your k3s. Have you followed the [instruction for installing Rasa X in an existing cluster](https://rasa.com/docs/rasa-x/installation-and-setup/install/quick-install-script#existing-cluster-installation)? If you intend to install Rasa X in a fresh k3s, please clean the existing cluster, and do it again. 

Please go to the [forum](https://forum.rasa.com) if you have follow-up questions.
