### ISSUE TITLE
[FR] Helm Chart improvements: priorityClassName

### ISSUE THREAD

**Issue by pierluigilenoci** [RasaHQ/rasa-x-helm#278]
It would be very helpful to have the ability to define `priorityClassName` for the deployments when installed with the chart.

Judging by the templates, this is currently not possible.

Ref:
* https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

**Comment by RASADSA** [comment]
@pierluigilenoci can you please elaborate in what scenario this would be a good measure ?

kubernetes has already via Node selectors and tagging a good way to make sure important pods / deployments are fenced of from other critical parts of the k8s ecosystem

> In a cluster where not all users are trusted, a malicious user could create Pods at the highest possible priorities, causing other Pods to be evicted/not get scheduled. An administrator can use ResourceQuota to prevent users from creating pods at high priorities.

changing priorityClassName of the rasa x helmchart would introduce a way to kill on a k8s node system critical pods via the rasa helmchart. 

security wise its a bad choice and it puts the k8s clusters stability at a high risk.

**Comment by pierluigilenoci** [comment]
@RASADSA the `priorityClass` has nothing to do with the choice of nodes.
As it has nothing to do with security.
It is to ensure that critical pods have priority in scheduling.

All pods have a priority in each case within the cluster.

Kubernetes has two priority classes by default which are used to prioritize critical pods.

`priorityClass` allows you to define additional levels of priority within a cluster, in addition to the predefined ones, to give different eviction risks to the various pods.

If a pod has no `priorityClass` it receives a score of 0.

Ref:
* https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
* https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

My FR requires to implement the ability to choose a `priorityClassName` for Rasa-x pods. 

Introducing the ability to assign a class does not mean assigning one.
The default value could be an empty string.

The scenario you are talking about could only be realized if one voluntarily assigned Rasa-X the same priority as one of the critical pods.

In this case, the problem is not the chart but lies between the chair and the keyboard.

**Comment by RASADSA** [comment]
@pierluigilenoci 

FR is denied out of multiple reasons:

- PriorityClass & priorityClassName are not needed to run a stable K8S deployment of RASA X at this point. 
- There are other K8S features that work well like nodeSelector to make sure that the K8S deployment is running healthy inside a cluster. 


Workaround:

afaik you use flux
kustomize patch will make your FR possible 

https://fluxcd.io/docs/components/kustomize/kustomization/
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/

hope this helps.

> In this case, the problem is not the chart but lies between the chair and the keyboard.

https://opensource.guide/best-practices/#keep-the-conversation-friendly

Opensource development in a nutshell

https://daniel.haxx.se/blog/2022/01/17/enforcing-the-pyramid-of-open-source/

closing the issue

**Comment by pierluigilenoci** [comment]
@RASADSA as usual, I accept it but I do not agree with the reasons which I find rather spurious.
Or affected by logical fallacies.

Maybe I wasn't clear enough in my previous answer and so I try to be again.
`nodeSelector` and` priorityClassName` are different things used for different purposes.
Although it is clear that you can also do without it but I think it was an interesting and harmless improvement for the chart.

**Comment by RASADSA** [comment]
@pierluigilenoci 

> @RASADSA as usual, I accept it but I do not agree with the reasons which I find rather spurious.
Or affected by logical fallacies.
Maybe I wasn't clear enough in my previous answer and so I try to be again. 

👉 https://opensource.guide/best-practices/#keep-the-conversation-friendly

basically you explained it yourself why this is a bad idea. 
But lets do a full circle on that:

> Kubernetes has two priority classes by default which are used to prioritize critical pods.
> priorityClass allows you to define additional levels of priority within a cluster, in addition to the predefined ones, to give different eviction risks to the various pods.
> If a pod has no priorityClass it receives a score of 0.

exactly. 

real world k8s production clusters scenario with k8s  

A team decided to use this the priorityClass feature. 
What they did was basically what you proposed.
Problem was that it was a shared k8s cluster with more then 30+ Nodes and a lot of deployments and namespaces.
nobody talked between the teams and also none of the kubernetes administrators where involved.
so they just have seen https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/ and because they wanted to be quicker on deployments or on other related speed problems to get faster on a system level (pod prioritisation always means you get the fastlane inside the k8s cluster)
they deployed their application with system-cluster-critical and system-node-critical - because it showed in there local k8s dev tests cluster (team was the only tennant) that this would be the efficient way.
some time later there where multiple incidents because the whole shares k8s cluster was shot down by their deployment.
Benchmarking if i remember correctly
there where some trials with the team in the end on creating their own PriorityClassName but that led to abuse too by the team.
In the end it was denied because of abuse.

Takeway

 RASA X helmchart is used by a wider audience and we will not introduce a feature that is not having any benefit for the application nor if the k8s cluster security can be easily compromised by priorityClass k8s features provided by our chart by default.
 RASA X is not a CSI / CNI or the k8s control plane of a kubernetes cluster - if this would be the case it would be different.
 
There are multiple other ways to patch this in if you want to have this in your deployment on your own cluster - its at your own risk to choose this.

and another good advice - change your tone and wording. 
Insulting people because they dont do what you want them to do - shows a lack of communication and its rather offensive to others.

cheers

**Comment by pierluigilenoci** [comment]
@RASADSA

Dear Daniel,
I'm sorry to have to inform you that your example is not a valid argument.

I try to explain the coarser reasons: 

* The `priorityClass` exist in Kubernetes.
Whether or not you put the ability to configure them in your chart, any team can still use them and create the problem you tell.
* Adding the ability to configure a `priorityClassName` does not mean that all Rasa users will use this ability.
Unless you force it into the chart by default.
This can be trivially achieved (or avoided).
* Adding the ability to configure a `priorityClassName` doesn't mean you have to add a `priorityClass` as well.
But it can be done with a low priority over critical pods so that you can avoid the problem.
* Improper use of these can lead to cluster stability problems.
It certainly doesn't compromise a cluster's security.

In reality, all your answer is not valid and, as I said in my previous comment, it is affected by some logical fallacies.

I'll refer you to the more explicit ones I found:

https://en.wikipedia.org/wiki/Slippery_slope
https://en.wikipedia.org/wiki/Faulty_generalization
https://en.wikipedia.org/wiki/Ad_hominem

Allow me to add a personal note.
I think the tone of my answer was sorry but not insulting.
If that's what you've perceived I'm sorry.
I have only tried to argue my reasons.
Using a professional tone and technical arguments.
If my technical notes on the merits offend you, it's out of my control.

Have a good life.
